### ISSUE TITLE
Chart and Headers

### ISSUE THREAD

**Issue by HilmiZul** [ditanursabila/TE-FA_PerpusDigital#1]
Hello,

I ran this project on my local machine and everything is pretty design, until I found some issue:

1. Chart unresponsive and didn't give space between labels and bottom edge
https://github.com/ditanursabila/TE-FA_PerpusDigital/blob/f120d4ea3b59fe42633adbffbf1799669747aacb/pages/index.vue#L52
![Chart unresponsive](https://fswtvokmcxzehzjjnarl.supabase.co/storage/v1/object/public/mybucket/review/review-rpl2-dita-1.png?t=2024-03-11T01%3A57%3A59.243Z)

2. Heading title are inconsistency and not same with Figma
https://github.com/ditanursabila/TE-FA_PerpusDigital/blob/f120d4ea3b59fe42633adbffbf1799669747aacb/pages/buku/index.vue#L8
https://github.com/ditanursabila/TE-FA_PerpusDigital/blob/f120d4ea3b59fe42633adbffbf1799669747aacb/pages/pengunjung/index.vue#L8
![Heading 1](https://fswtvokmcxzehzjjnarl.supabase.co/storage/v1/object/public/mybucket/review/review-rpl2-dita-2.png)
![Heading 2](https://fswtvokmcxzehzjjnarl.supabase.co/storage/v1/object/public/mybucket/review/review-rpl2-dita-3.png)

Hope you enjoy to fix it in this long weekend.

Thanks.

**Comment by ditanursabila** [comment]
It's been updated, sir🙏
Thank You

**Comment by HilmiZul** [comment]
one more thing, you still fix back button.

![can't reach back button](https://fswtvokmcxzehzjjnarl.supabase.co/storage/v1/object/public/mybucket/review/review-rpl2-dita-4.png)

Thanks.

**Comment by ditanursabila** [comment]
It's been fixed sir, thank you😁🙏
